name: Pr Labeler
on: pull_request

concurrency:
  group: labeler-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  label:
    name: Label pr
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/config/labeler_config.yml
          sync-labels: true
